# -*- coding: utf-8 -*-
"""oasis_taask1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OH8P8u52Vp2c4TdnRM3UBVIB4tPz3aDc
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/Iris.csv')
df.head(150)

df.info()

from matplotlib import pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

df0=df[df.Species=="Iris-setosa"]
df1=df[df.Species=="Iris-versicolor"]
df2=df[df.Species=="Iris-virginica "]

df.drop(['Id'],axis=1,inplace=True)

plt.xlabel('SepalLengthCm')
plt.ylabel('SepalWidthCm')

plt.scatter(df0['SepalLengthCm'],df0['SepalWidthCm'],color='blue',marker='+')
plt.scatter(df1['SepalLengthCm'],df1['SepalWidthCm'],color='green',marker='*')

plt.xlabel('PeatlLengthCm')
plt.ylabel('PetalWidthCm')

plt.scatter(df0['PetalLengthCm'],df0['PetalWidthCm'],color='blue',marker='+')
plt.scatter(df1['PetalLengthCm'],df1['PetalWidthCm'],color='green',marker='*')

from sklearn.model_selection import train_test_split

X = df.drop(["Species"], axis='columns')
X.head()

y = df.Species
y.head()

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

len(X_train)

len(X_test)

from sklearn.svm import SVC
model = SVC()

model.fit(X_train,y_train)

x_new = np.array([[5, 2.9, 1, 0.2]])
prediction = model.predict(x_new)
print("Prediction: {}".format(prediction))